export const katakanaDictionary = {
    "アパート": { romaji: "apaato", meaning: "apartment" },
    "アベック": { romaji: "abekku", meaning: "romantic couple" },
    "アイドル": { romaji: "aidoru", meaning: "(teen) idol" },
    "アイス": { romaji: "aisu", meaning: "ice" },
    "アイスクリーム": { romaji: "aisukuriimu", meaning: "ice cream" },
    "アイゼン": { romaji: "aizen", meaning: "crampons" },
    "アメフト": { romaji: "amefuto", meaning: "American football" },
    "アメリカンドッグ": { romaji: "amerikandoggu", meaning: "corn dog" },
    "アニメ": { romaji: "anime", meaning: "animation" },
    "アニソン": { romaji: "anison", meaning: "an anime song" },
    "アンケート": { romaji: "ankeeto", meaning: "questionnaire" },
    "アンニュイ": { romaji: "annyui", meaning: "ennui" },
    "アンサー": { romaji: "ansaa", meaning: "reply to a question" },
    "アパート": { romaji: "apaato", meaning: "apartment (US)" },
    "アポ": { romaji: "apo", meaning: "appointment" },
    "アロエ": { romaji: "aroe", meaning: "aloe" },
    "アルバイト": { romaji: "arubaito", meaning: "part-time job" },
    "アールブイ": { romaji: "aarubui", meaning: "truck" },
    "アルコール": { romaji: "arukooru", meaning: "álcool" },
    "アウトコース": { romaji: "autokoosu", meaning: "outside" },
    "バーゲン": { romaji: "baagen", meaning: "a sale at a store" },
    "バイキング": { romaji: "baikingu", meaning: "smorgasbord" },
    "バイク": { romaji: "baiku", meaning: "a motorcycle" },
    "バカンス": { romaji: "bakansu", meaning: "holiday" },
    "ブックカバー": { romaji: "bukkukabaa", meaning: "dust jacket" },
    "バックミラー": { romaji: "bakkumiraa", meaning: "rear-view mirror" },
    "バックナンバー": { romaji: "bakkunanbaa", meaning: "back issue" },
    "バックネット": { romaji: "bakkunetto", meaning: "a backstop (in baseball)" },
    "バリアフリー": { romaji: "bariafurii", meaning: "Accessible facilities for handicapped persons" },
    "バリカン": { romaji: "barikan", meaning: "Hand or electric operating hair trimmer" },
    "バター": { romaji: "bataa", meaning: "butter" },
    "バッティング": { romaji: "battingu", meaning: "Swing the bat in baseball" },
    "ベビーカー": { romaji: "bebiikaa", meaning: "stroller (US)" },
    "ベッドタウン": { romaji: "beddotaun", meaning: "bedroom suburbs" },
    "ビジネスホテル": { romaji: "bijinesuhoteru", meaning: "budget hotel" },
    "ビロード": { romaji: "biroodo", meaning: "velvet" },
    "ビル": { romaji: "biru", meaning: "building (especially modern steel / concrete buildings)" },
    "ビール": { romaji: "biiru", meaning: "beer" },
    "ボンベ": { romaji: "bonbe", meaning: "a steel canister for storing pressurized gas" },
    "ボタン": { romaji: "botan", meaning: "button" },
    "ブランコ": { romaji: "buranko", meaning: "a swing" },
    "ブレザー": { romaji: "burezaa", meaning: "blazer" },
    "ブルマ": { romaji: "buruma", meaning: "short pants worn for exercise by girls" },
    "チアリーダー": { romaji: "chiariidaa", meaning: "cheerleader" },
    "チアリーディング": { romaji: "chiariidingu", meaning: "cheerleading" },
    "チケット": { romaji: "chiketto", meaning: "ticket" },
    "チンキ": { romaji: "chinki", meaning: "tincture" },
    "チューハイ or 酎ハイ": { romaji: "chuuhai", meaning: "a kind of alcoholic drink originating from Japan" },
    "コラボ": { romaji: "korabo", meaning: "A term for when two separate entities come together and make something" },
    "デパート": { romaji: "depaato", meaning: "department store" },
    "デッサン": { romaji: "dessan", meaning: "drawing" },
    "デスク": { romaji: "desuku", meaning: "an editor for a certain section of a publication" },
    "ドイツ": { romaji: "doitsu", meaning: "Deutsch(land)" },
    "ドンマイ": { romaji: "donmai", meaning: "'dont worry about it'" },
    "ドライバー": { romaji: "doraibaa", meaning: "a screwdriver" },
    "ドライブイン": { romaji: "doraibuin", meaning: "rest area" },
    "ドラマ": { romaji: "dorama", meaning: "TV drama" },
    "ドリフト": { romaji: "dorifuto", meaning: "drifting" },
    "エアコン": { romaji: "eakon", meaning: "air conditioning or air conditioner" },
    "エキス": { romaji: "ekisu", meaning: "extract" },
    "エネルギッシュ": { romaji: "enerugisshu", meaning: "energetic" },
    "エンスト": { romaji: "ensuto", meaning: "stall (as in an automobile engine)" },
    "エレベーター": { romaji: "erebeetaa", meaning: "elevator (American English)" },
    "エール": { romaji: "eeru", meaning: "(1) to cheer on a player in a sports competition; (2) to express support for a candidate in an election" },
    "エスカレーター": { romaji: "esukareetaa", meaning: "escalator" },
    "エステ": { romaji: "esute", meaning: "beauty salon" },
    "エッチ": { romaji: "etchi", meaning: "dirty" },
    "ファイナル": { romaji: "fainaru", meaning: "last" },
    "ファミコン": { romaji: "famikon", meaning: "fami(ly) com(puter)" },
    "ファンファーレ": { romaji: "fanfaare", meaning: "a musical fanfare" },
    "ファンタジック": { romaji: "fantajikku", meaning: "fantastic" },
    "フェッチ": { romaji: "fetchi", meaning: "(Computer Jargon) To fetch an instruction from main memory when a microprocessor executes a command" },
    "フォアボール": { romaji: "foabooru", meaning: "walk" },
    "フライ": { romaji: "furai", meaning: "fly ball (baseball term)" },
    "フライ": { romaji: "furai", meaning: "Deep frying" },
    "フリーター": { romaji: "furiitaa", meaning: "underemployed young adults" },
    "フロント": { romaji: "furonto", meaning: "the reception desk" },
    "ガラス or 硝子": { romaji: "garasu", meaning: "glass (material)" },
    "ガーゼ": { romaji: "gaaze", meaning: "gauze" },
    "ゲレンデ": { romaji: "gerende", meaning: "ski slope" },
    "ゴム": { romaji: "gomu", meaning: "rubber" },
    "ググる": { romaji: "guguru", meaning: "to google" },
    "グラス": { romaji: "gurasu", meaning: "drinking glass" },
    "グロ": { romaji: "guro", meaning: "grotesque" },
    "ギャラリー": { romaji: "gyararii", meaning: "an art gallery" },
    "ハイカラ": { romaji: "haikara", meaning: "In 1920s slang" },
    "ハイネック": { romaji: "hainekku", meaning: "A turtleneck style shirt or sweater" },
    "ハイタッチ": { romaji: "haitatchi", meaning: "High five" },
    "ハッカー": { romaji: "hakkaa", meaning: "refers specifically to a computer black hat" },
    "ハモる": { romaji: "hamoru", meaning: "to harmonize (when singing)" },
    "ハンバーグ": { romaji: "hanbaagu", meaning: "Salisbury steak" },
    "ハンドル": { romaji: "handoru", meaning: "steering wheel or bicycle handlebars" },
    "ハンカチ": { romaji: "hankachi", meaning: "handkerchief" },
    "ハンスト": { romaji: "hansuto", meaning: "hunger strike" },
    "ハウス": { romaji: "hausu", meaning: "greenhouse or glasshouse" },
    "ヒステリー": { romaji: "hisuterii", meaning: "loss of (self) control" },
    "ヒップ": { romaji: "hippu", meaning: "buttocks" },
    "ホルモン": { romaji: "horumon", meaning: "hormone; also offal when served for yakiniku or hotpot" },
    "ホース": { romaji: "hoosu", meaning: "a hose" },
    "ホッチキス": { romaji: "hotchikisu", meaning: "stapler (a genericized trademark of the E. H. Hotchkiss company" },
    "ホーム": { romaji: "hoomu", meaning: "a railway platform" },
    "イエス": { romaji: "iesu", meaning: "Jesus" },
    "イギリス": { romaji: "igirisu", meaning: "English" },
    "イクラ": { romaji: "ikura", meaning: "salmon roe" },
    "イメージ": { romaji: "imeeji", meaning: "an image" },
    "インフレ": { romaji: "infure", meaning: "inflation" },
    "イラスト": { romaji: "irasuto", meaning: "an illustration" },
    "ジャンパー": { romaji: "janpaa", meaning: "jacket" },
    "ジンギスカン": { romaji: "jingisukan", meaning: "Jingisukan (Mongolian style barbecue with cut lamb and vegetables)" },
    "ジーパン": { romaji: "jiipan", meaning: "jeans" },
    "ジュース": { romaji: "juusu", meaning: "often used to refer to soda or energy drinks" },
    "カメラマン": { romaji: "kameraman", meaning: "photographer" },
    "カン": { romaji: "kan", meaning: "can (beverage can or tin can)" },
    "カンニング": { romaji: "kanningu", meaning: "cheating" },
    "カッパ": { romaji: "kappa", meaning: "(rain) coat" },
    "カラン": { romaji: "karan", meaning: "faucet" },
    "カラオケ": { romaji: "karaoke", meaning: "empty) + orche(stra)" },
    "カルキ": { romaji: "karuki", meaning: "lime (mineral)" },
    "カルピス": { romaji: "karupisu", meaning: "Calpis (a milky soft drink)" },
    "カルタ": { romaji: "karuta", meaning: "karuta (Japanese playing cards)" },
    "カルテ": { romaji: "karute", meaning: "(a patients) medical record" },
    "コーヒー": { romaji: "koohii", meaning: "coffee" },
    "コック": { romaji: "kokku", meaning: "a cook" },
    "コミカライズ": { romaji: "komikaraizu", meaning: "to make a comic strip (manga) version of an originally non-comic strip title" },
    "コンビニ": { romaji: "konbini", meaning: "convenience store" },
    "コンビナート": { romaji: "konbinaato", meaning: "Combine (enterprise)" },
    "コンクール": { romaji: "konkuuru", meaning: "a contest" },
    "コンセント": { romaji: "konsento", meaning: "power outlet" },
    "コント": { romaji: "konto", meaning: "a short comedy" },
    "コップ": { romaji: "koppu", meaning: "a glass or tumbler" },
    "コラーゲン": { romaji: "koraagen", meaning: "collagen" },
    "コロッケー": { romaji: "korokkee", meaning: "croquette" },
    "コスプレ": { romaji: "kosupure", meaning: "cosplay (a subculture involving dressing up in costumes" },
    "クラブ": { romaji: "kurabu", meaning: "a club or society" },
    "クラクション": { romaji: "kurakushon", meaning: "horn (on an automobile)" },
    "クランケ": { romaji: "kuranke", meaning: "patient" },
    "クレーム": { romaji: "kureemu", meaning: "a complaint" },
    "クリスタル": { romaji: "kurisutaru", meaning: "shiny or clear" },
    "キーボード": { romaji: "kiiboodo", meaning: "a keyboard" },
    "キャベツ": { romaji: "kyabetsu", meaning: "cabbage" },
    "キャンペーン": { romaji: "kyanpeen", meaning: "a sales campaign or sweepstakes" },
    "キャップ": { romaji: "kyappu", meaning: "cap" },
    "ママ": { romaji: "mama", meaning: "mom" },
    "マンダラ": { romaji: "mandara", meaning: "circle" },
    "マニア": { romaji: "mania", meaning: "enthusiasm" },
    "マンション": { romaji: "manshon", meaning: "modern concrete apartment / condominium block" },
    "マロン": { romaji: "maron", meaning: "chestnut" },
    "マスコミ": { romaji: "masukomi", meaning: "mass media" },
    "メーカー": { romaji: "meekaa", meaning: "manufacturer" },
    "メール": { romaji: "meeru", meaning: "e-mail" },
    "ミイラ": { romaji: "miira", meaning: "a mummy" },
    "ミルク": { romaji: "miruku", meaning: "milk" },
    "ミシン": { romaji: "mishin", meaning: "sewing machine" },
    "モバイル": { romaji: "mobairu", meaning: "mobile communications" },
    "ムーディ": { romaji: "muudi", meaning: "nice" },
    "ナイター": { romaji: "naitaa", meaning: "a night game" },
    "ニート　or NEET": { romaji: "niito", meaning: "Education or Training" },
    "ノルマ": { romaji: "noruma", meaning: "quota" },
    "ノート": { romaji: "nooto", meaning: "a notebook" },
    "オーディエンス": { romaji: "oodiensu", meaning: "group of people who participate in a show" },
    "オフ": { romaji: "ofu", meaning: "a sale at a store; e.g." },
    "オペ": { romaji: "ope", meaning: "surgical operation" },
    "オーライ": { romaji: "oorai", meaning: "all correctAnswersCount" },
    "オルゴール": { romaji: "orugooru", meaning: "a music box or any instrument that operates off of a music roll such as a calliope" },
    "オートバイ": { romaji: "ootobai", meaning: "motorcycle" },
    "パイン": { romaji: "pain", meaning: "pineapple" },
    "パーマ": { romaji: "paama", meaning: "perm" },
    "パン": { romaji: "pan", meaning: "pan" },
    "パネリスト": { romaji: "panerisuto", meaning: "panelist" },
    "パンク": { romaji: "panku", meaning: "flat tire" },
    "パンスト": { romaji: "pansuto", meaning: "pantyhose" },
    "パソコン": { romaji: "pasokon", meaning: "PC" },
    "パンツ": { romaji: "pantsu", meaning: "underpants (American English)" },
    "パパ": { romaji: "papa", meaning: "dad" },
    "ペチカ": { romaji: "pechika", meaning: "Russian oven" },
    "ペンション": { romaji: "penshon", meaning: "a resort hotel / chalet / cottage" },
    "ピエロ": { romaji: "piero", meaning: "a clown" },
    "ピーマン": { romaji: "piiman", meaning: "sweet bell pepper" },
    "ピッケル": { romaji: "pikkeru", meaning: "ice axe" },
    "ピンチ": { romaji: "pinchi", meaning: "potentially disastrous situation" },
    "ピンセット": { romaji: "pinsetto", meaning: "tweezers" },
    "ポエマー": { romaji: "poemaa", meaning: "a poet" },
    "ポケベル": { romaji: "pokeberu", meaning: "beeper" },
    "ポケモン": { romaji: "pokemon", meaning: "Pokémon" },
    "ポンプ": { romaji: "ponpu", meaning: "pump" },
    "ポシェット": { romaji: "poshetto", meaning: "a small bag" },
    "ポスト": { romaji: "posuto", meaning: "a mailbox (US)" },
    "プロフィール": { romaji: "purofiiru", meaning: "a profile" },
    "プロレス": { romaji: "puroresu", meaning: "professional wrestling" },
    "ライバル": { romaji: "raibaru", meaning: "A fellow competitor or an enemy" },
    "ライフライン": { romaji: "raifurain", meaning: "infrastructure" },
    "ラッコ": { romaji: "rakko", meaning: "a sea otter" },
    "ランドセル": { romaji: "randoseru", meaning: "a hard schoolbag" },
    "レジュメ": { romaji: "rejume", meaning: "a resume" },
    "レントゲン": { romaji: "rentogen", meaning: "X-ray" },
    "レストラン": { romaji: "resutoran", meaning: "restaurant" },
    "リベンジ": { romaji: "ribenji", meaning: "return match" },
    "リフォーム": { romaji: "rifoomu", meaning: "remodel" },
    "リモコン": { romaji: "rimokon", meaning: "remote control" },
    "リニューアル": { romaji: "rinyuuaru", meaning: "remodeling" },
    "リストラ": { romaji: "risutora", meaning: "(noun) restructuring" },
    "ロマン": { romaji: "roman", meaning: "novel" },
    "ロープウェー": { romaji: "roopuwee", meaning: "ropeway" },
    "ルー": { romaji: "ruu", meaning: "roux" },
    "ルポ": { romaji: "rupo", meaning: "Reportage" },
    "リュックサック": { romaji: "ryukkusakku", meaning: "backpack" },
    "サービス": { romaji: "saabisu", meaning: "service" },
    "サボる": { romaji: "saboru", meaning: "to slack off" },
    "サイダー": { romaji: "saidaa", meaning: "a kind of soda unrelated to actual cider" },
    "サイン": { romaji: "sain", meaning: "signature" },
    "サインペン": { romaji: "sainpen", meaning: "marker" },
    "サンドイッチ or サンド": { romaji: "sandoitchi", meaning: "sand(wich)" },
    "サンドバッグ": { romaji: "sandobaggu", meaning: "punching bag" },
    "サラダ": { romaji: "sarada", meaning: "salad" },
    "サラリーマン": { romaji: "sarariiman", meaning: "salaryman: a salaried office/white collar worker" },
    "センス": { romaji: "sensu", meaning: "understanding of subtleties" },
    "セツナ": { romaji: "setsuna", meaning: "moment" },
    "シーエム": { romaji: "shiiemu", meaning: "television commercial" },
    "シール": { romaji: "shiiru", meaning: "sticker" },
    "シュークリーム": { romaji: "shuukuriimu", meaning: "a cream puff" },
    "ソフト": { romaji: "sofuto", meaning: "video game console or computer software; also used to describe tasks or work (such as design) requiring imagination" },
    "スカイ": { romaji: "sukai", meaning: "a bib" },
    "スケボー": { romaji: "sukeboo", meaning: "skateboard" },
    "スケルトン": { romaji: "sukeruton", meaning: "translucent" },
    "スキー": { romaji: "sukii", meaning: "used as a noun to refer to skiing" },
    "スコップ": { romaji: "sukoppu", meaning: "trowel" },
    "スマート": { romaji: "sumaato", meaning: "slim" },
    "スマホ": { romaji: "sumaho", meaning: "smartphone" },
    "スムーズ": { romaji: "sumuuzu", meaning: "When a plan or transaction happens without incident" },
    "スーパー": { romaji: "suupaa", meaning: "supermarket" },
    "スピン": { romaji: "supin", meaning: "a ribbon or tassel on a book" },
    "スポイト": { romaji: "supoito", meaning: "syringe" },
    "ストーブ": { romaji: "sutoobu", meaning: "space heater" },
    "タイムリー": { romaji: "taimurii", meaning: "a clutch hit (in baseball)" },
    "タレント": { romaji: "tarento", meaning: "TV personality/celebrity" },
    "テーマ": { romaji: "teema", meaning: "theme" },
    "テンキー": { romaji: "tenkii", meaning: "numeric keypad" },
    "テンション": { romaji: "tenshon", meaning: "a state of excitement" },
    "テレビ": { romaji: "terebi", meaning: "television" },
    "テレフォン": { romaji: "terefon", meaning: "a system that converts acoustic vibrations to electrical signals in order to transmit sound" },
    "テレカ": { romaji: "tereka", meaning: "prepaid card for using public telephones" },
    "ティーンエージャー": { romaji: "tiineejaa", meaning: "A person in their teens" },
    "トーチカ": { romaji: "toochika", meaning: "bunker" },
    "トイレ": { romaji: "toire", meaning: "toilet" },
    "トランプ": { romaji: "toranpu", meaning: "playing cards" },
    "トレーナー": { romaji: "toreenaa", meaning: "a sweat shirt" },
    "ワープロ": { romaji: "waapuro", meaning: "word processor" },
    "ヨット": { romaji: "yotto", meaning: "a sailboat or yacht" },
    "ゼン": { romaji: "zen", meaning: "a meditation" },
    "ゼロ": { romaji: "zero", meaning: "zero" },
    "トマト": { romaji: "tomato", meaning: "tomato" },
    "アフターサービス": { romaji: "afutaasaabisu", meaning: "customer service" },
    "ボールペン": { romaji: "boorupen", meaning: "a ballpoint pen" },
    "キャビンアテンダント": { romaji: "kyabinatendanto", meaning: "A flight attendant" },
    "コンピューター": { romaji: "konpyuutaa", meaning: "computer" },
    "ダブル(noun)": { romaji: "daburu", meaning: "double" },
    "ダンプカー": { romaji: "danpukaa", meaning: "dump truck (US)" },
    "ダストボックス": { romaji: "dasutobokkusu", meaning: "rubbish bin (UK)" },
    "デッドボール": { romaji: "deddobooru", meaning: "hit by a pitch" },
    "デコレーションケーキ": { romaji: "dekoreeshonkeeki", meaning: "a fancy cake" },
    "ドクター ストップ": { romaji: "dokutaasutoppu", meaning: "when the doctor tells a patient to stop doing something" },
    "フライドポテト": { romaji: "furaidopoteto", meaning: "french fries (US)" },
    "フリーダイアル": { romaji: "furiidaiaru", meaning: "toll free call" },
    "フリーサイズ": { romaji: "furiisaizu", meaning: "one-size-fits-all" },
    "フロントガラス": { romaji: "furontogarasu", meaning: "windshield (US)" },
    "ガードマン": { romaji: "gaadoman", meaning: "a (private) security guard" },
    "ガソリンスタンド": { romaji: "gasorinsutando", meaning: "gas station (US)" },
    "ガッツポーズ": { romaji: "gattsupoozu", meaning: "fist pump" },
    "ゲームセンター": { romaji: "geemusentaaorgeesen", meaning: "video arcade" },
    "ゴールデンアワー": { romaji: "goorudenawaa", meaning: "prime time in Japanese television" },
    "ゴールデンウィーク": { romaji: "goorudenwiiku", meaning: "A week of holidays in Japan" },
    "ハッピーエンド": { romaji: "happiiendo", meaning: "a happy ending" },
    "ハンドルキーパー": { romaji: "handorukiipaa", meaning: "designated driver" },
    "ハンドルネーム": { romaji: "handoruneemu", meaning: "handle" },
    "ヘアピンカーブ": { romaji: "heapinkaabu", meaning: "hairpin turn" },
    "ヘルスメーター": { romaji: "herusumeetaa", meaning: "bathroom scales" },
    "ホットケーキ": { romaji: "hottokeeki", meaning: "a pancake" },
    "ホワイトデー": { romaji: "howaitodee", meaning: "White Day" },
    "イン・キー": { romaji: "inkii", meaning: "locking ones car keys inside of ones car" },
    "ジェンダーフリー": { romaji: "jendaafurii", meaning: "gender equality" },
    "ジェットコースター": { romaji: "jettokoosutaa", meaning: "roller coaster" },
    "カモン": { romaji: "kamon", meaning: "An invitation to join an activity" },
    "カリウム": { romaji: "kariumuorkari", meaning: "potassium" },
    "カシューナッツ": { romaji: "Kashuunattsu", meaning: "cashew" },
    "カステラ": { romaji: "kasutera", meaning: "a kind of sponge cake popular at festivals and as a street food in Japan" },
    "キーホルダー": { romaji: "kiihorudaa", meaning: "key ring" },
    "キスマーク": { romaji: "kisumaaku", meaning: "hickey" },
    "キッチンペーパー": { romaji: "kitchinpeepaa", meaning: "paper towel" },
    "コインランドリー": { romaji: "koinrandorii", meaning: "laundromat (US)" },
    "コインロッカー": { romaji: "koinrokkaa", meaning: "type of locker" },
    "キャンピングカー": { romaji: "kyanpingukaa", meaning: "a recreational vehicle" },
    "キャッチボール": { romaji: "kyatchibooru", meaning: "the game of catch" },
    "キャッチホン": { romaji: "kyatchihon", meaning: "call waiting" },
    "キャッチコピー": { romaji: "kyatchikopii", meaning: "tagline" },
    "マグカップ": { romaji: "magukappu", meaning: "mug" },
    "マイナスドライバー": { romaji: "mainasudoraibaa", meaning: "(flathead) screwdriver" },
    "マジックテープ": { romaji: "majikkuteepu", meaning: "Velcro" },
    "メールマガジン": { romaji: "meerumagajin", meaning: "e-mail newsletter" },
    "モーニングコール": { romaji: "mooningukooru", meaning: "wake-up call" },
    "モーニングコート": { romaji: "mooningukooto", meaning: "morning coat" },
    "モーニングサービス": { romaji: "mooningusaabisu", meaning: "breakfast special" },
    "ナンバーディスプレイ": { romaji: "nanbaadisupurei", meaning: "caller ID" },
    "ナンバープレート": { romaji: "nanbaapureeto", meaning: "number plate" },
    "ノークレームノーリターン": { romaji: "nookureemunooritaan", meaning: "no return" },
    "オープンカー": { romaji: "oopunkaa", meaning: "convertible (automobile)" },
    "パーソナルコンピューター": { romaji: "paasonarukonpyuutaa", meaning: "personal computer" },
    "ペアルック": { romaji: "pearukku", meaning: "matching outfits (usually between a couple)" },
    "ペーパーカンパニー": { romaji: "peepaakanpanii", meaning: "dummy company" },
    "ペーパードライバー": { romaji: "peepaadoraibaa", meaning: "a person who has a drivers license but does not usually drive (i.e.: a driver only on paper)" },
    "ペーパーテスト": { romaji: "peepaatesuto", meaning: "written examination/test" },
    "プラスアルファ": { romaji: "purasuarufa", meaning: "in addition" },
    "プラスドライバー": { romaji: "purasudoraibaa", meaning: "Phillips screwdriver" },
    "プレイガイド": { romaji: "pureigaido", meaning: "(theater) ticket agency" },
    "プッシュホン": { romaji: "pusshuhon", meaning: "touch-tone phone" },
    "ライブアクション": { romaji: "raibuakushon", meaning: "animated" },
    "ライブハウス": { romaji: "raibuhausu", meaning: "club with live music" },
    "ランニングホームラン": { romaji: "ranninguhoomuran", meaning: "an inside-the-park home run" },
    "ランニングシャツ": { romaji: "ranningushatsu", meaning: "a sleeveless T-shirt" },
    "リードオンリーメンバー": { romaji: "riidoonriimenbaa", meaning: "an internet lurker" },
    "リンクフリー": { romaji: "rinkufurii", meaning: "free to link" },
    "リサイクルショップ": { romaji: "risaikurushoppu", meaning: "secondhand shop (selling used" },
    "ロードショー": { romaji: "roodoshoo", meaning: "premiere" },
    "ロマンスグレー": { romaji: "romansuguree", meaning: "silver-gray hair" },
    "ロマンスカー": { romaji: "romansukaa", meaning: "deluxe train" },
    "ロスタイム": { romaji: "rosutaimu", meaning: "added time" },
    "サイドブレーキ": { romaji: "saidobureeki", meaning: "hand brake" },
    "シルバーシート": { romaji: "shirubaashiito", meaning: "priority seating on public transportation" },
    "ソフトクリーム": { romaji: "sofutokuriimu", meaning: "soft serve (ice cream)" },
    "ソーラーシステム": { romaji: "sooraashisutemu", meaning: "a solar battery" },
    "スイートルーム": { romaji: "suiitoruumu", meaning: "a suite in a hotel" },
    "スリーサイズ": { romaji: "suriisaizu", meaning: "three primary female body measurements (bust" },
    "ストライキ": { romaji: "sutoraiki", meaning: "labor strike" },
    "ストレートティー": { romaji: "sutoreetotii", meaning: "black tea without milk" },
    "スーツアクター": { romaji: "suutsuakutaa", meaning: "suit actor" },
    "タバコ": { romaji: "tabako", meaning: "tabaco" },
    "タイムオーバー": { romaji: "taimuoobaa", meaning: "when a time limit has been reached" },
    "タオルケット": { romaji: "taoruketto", meaning: "a type of blanket made of a material similar to a beach" },
    "テレビゲーム": { romaji: "terebigeemu", meaning: "video game" },
    "トレーニングパンツ": { romaji: "toreeningupantsu", meaning: "pants for toddlers" },
    "ウィンカー": { romaji: "winkaa", meaning: "turn signal" },
    "ヴァージンロード": { romaji: "vaajinroodo", meaning: "the aisle (in a Western-style" },
    "ワイドショー": { romaji: "waidoshoo", meaning: "talk show" },
    "ワイシャツ": { romaji: "waishatsu", meaning: "dress shirt (of any color)" },
    "ワンパターン": { romaji: "wanpataan", meaning: "of (artificial" },
    "ワンピース": { romaji: "wanpiisu", meaning: "(a single-piece) dress" },
    "ヤンエグ": { romaji: "yanegu", meaning: "young executive" },
    "ヨードチンキ": { romaji: "yoodochinki", meaning: "tincture of iodine" },
    "ユニットバス": { romaji: "yunittobasu", meaning: "modular bath" },
    "Uターンラッシュ": { romaji: "yuutaanrasshu", meaning: "the rush of traffic and people" },
    "ゼミナール": { romaji: "zeminaaru", meaning: "seminar" },
    "テスト": { romaji: "tesuto", meaning: "test" },
    "デパート": { romaji: "depaato", meaning: "department store" },
    "テレビ": { romaji: "terebi", meaning: "TV" },
    "テープ": { romaji: "teepu", meaning: "tape" },
    "テーブル": { romaji: "teeburu", meaning: "table" },
    "ドア": { romaji: "doa", meaning: "door" },
    "トイレ": { romaji: "toire", meaning: "toilet, lavatory" },
    "ネクタイ": { romaji: "nekutai", meaning: "necktie" },
    "ノート": { romaji: "nooto", meaning: "notebook" },
    "パーテイー": { romaji: "paateii", meaning: "party" },
    "キロ": { romaji: "kiro", meaning: "kg" },
    "キロ": { romaji: "kiro", meaning: "km" },
    "ワイシャツ": { romaji: "waishatsu", meaning: "white shirt" },
    "クラス": { romaji: "kurasu", meaning: "class" },
    "グラム": { romaji: "guramu", meaning: "gram" },
    "ストーブ": { romaji: "sutoobu", meaning: "stove, heater" },
    "スプーン": { romaji: "supuun", meaning: "spoon" },
    "スポーツ": { romaji: "supootsu", meaning: "sports" },
    "ズボン": { romaji: "zubon", meaning: "trousers" },
    "スリッパ": { romaji: "surippa", meaning: "slipper" },
    "シャツ": { romaji: "shatsu", meaning: "shirt" },
    "ギター": { romaji: "gitaa", meaning: "guitar" },
    "ナイフ": { romaji: "naifu", meaning: "knife" },
    "マッチ": { romaji: "machi", meaning: "matches" },
    "スカート": { romaji: "sukaato", meaning: "skirt" },
    "カレンダー": { romaji: "karendaa", meaning: "calendar" },
    "レコード": { romaji: "rekoodo", meaning: "record" },
    "メートル": { romaji: "meetoru", meaning: "meter" },
    "ゼロ": { romaji: "zero", meaning: "zero" },
    "レストラン": { romaji: "resutoran", meaning: "restaurant" },
    "ラジオ": { romaji: "rajio", meaning: "radio" },
    "コート": { romaji: "kooto", meaning: "coat" },
    "ページ": { romaji: "peeji", meaning: "page" },
    "ベッド": { romaji: "beddo", meaning: "bed" },
    "フィルム": { romaji: "firumu", meaning: "film" },
    "プール": { romaji: "puuru", meaning: "pool" },
    "フォーク": { romaji: "fooku", meaning: "fork" },
    "ポケット": { romaji: "poketto", meaning: "pocket" },
    "ボールペン": { romaji: "boorupen", meaning: "ballpen" },
    "ボタン": { romaji: "botan", meaning: "button" },
    "ホテル": { romaji: "hoteru", meaning: "hotel" },
    "エレベータ": { romaji: "erebeeta", meaning: "elevator" },
    "ハンカチ": { romaji: "hankachi", meaning: "handkerchief" },
    "ニュース": { romaji: "nyuusu", meaning: "news" },
    "コップ": { romaji: "koppu", meaning: "cup, glass" },
    "バス": { romaji: "basu", meaning: "bus" },
    "パン": { romaji: "pan", meaning: "bread" },
    "セーター": { romaji: "seetaa", meaning: "sweater" },
}

export const hiraganaDictionary = [
    { kana: "あう", romaji: "au", meaning: "to meet" },
    { kana: "あく", romaji: "aku", meaning: "to open" },
    { kana: "あける", romaji: "akeru", meaning: "to open" },
    { kana: "あげる", romaji: "ageru", meaning: "to give" },
    { kana: "あそぶ", romaji: "asobu", meaning: "to play" },
    { kana: "あびる", romaji: "abiru", meaning: "to take a shower" },
    { kana: "あらう", romaji: "arau", meaning: "to wash" },
    { kana: "ある", romaji: "aru", meaning: "to be, to exist" },
    { kana: "ある", romaji: "aru", meaning: "to possess" },
    { kana: "あるく", romaji: "aruku", meaning: "to walk" },
    { kana: "いう", romaji: "iu", meaning: "to say, to tell" },
    { kana: "いく", romaji: "iku", meaning: "to go" },
    { kana: "いる", romaji: "iru", meaning: "need, must haven be required" },
    { kana: "いる", romaji: "iru", meaning: "to exist" },
    { kana: "いれる", romaji: "ireru", meaning: "to insert, to put in" },
    { kana: "うたう", romaji: "utau", meaning: "to sing" },
    { kana: "うまれる", romaji: "umareru", meaning: "to be born" },
    { kana: "うる", romaji: "uru", meaning: "to sell" },
    { kana: "おきる", romaji: "okiru", meaning: "to get up, to stand up" },
    { kana: "おく", romaji: "oku", meaning: "to put" },
    { kana: "おくる", romaji: "okuru", meaning: "to send" },
    { kana: "おす", romaji: "osu", meaning: "to push" },
    { kana: "おぼえる", romaji: "oboeru", meaning: "to memorize, to remember" },
    { kana: "およぐ", romaji: "oyogu", meaning: "to swim" },
    { kana: "おりる", romaji: "oriru", meaning: "to get off" },
    { kana: "おわる", romaji: "owaru", meaning: "to end" },
    { kana: "かう", romaji: "kau", meaning: "to buy" },
    { kana: "かえす", romaji: "kaesu", meaning: "to return an object" },
    { kana: "かえる", romaji: "kaeru", meaning: "to return home" },
    { kana: "かかる", romaji: "kakaru", meaning: "to take time or money" },
    { kana: "かく", romaji: "kaku", meaning: "to write" },
    { kana: "かける", romaji: "kakeru", meaning: "to wear" },
    { kana: "かける", romaji: "kakeru", meaning: "to make a phone call" },
    { kana: "かす", romaji: "kasu", meaning: "to lend" },
    { kana: "かぶる", romaji: "kaburu", meaning: "to put on a hat" },
    { kana: "かりる", romaji: "kariru", meaning: "to borrow" },
    { kana: "きえる", romaji: "kieru", meaning: "to go out, to vanish" },
    { kana: "きく", romaji: "kiku", meaning: "to listen" },
    { kana: "きる", romaji: "kiru", meaning: "to cut" },
    { kana: "きる", romaji: "kiru", meaning: "to wear, to put on" },
    { kana: "くる", romaji: "kuru", meaning: "to come" },
    { kana: "けす", romaji: "kesu", meaning: "to turn off, to switch off" },
    { kana: "こたえる", romaji: "kotaeru", meaning: "to answer" },
    { kana: "こまる", romaji: "komaru", meaning: "to be in trouble" },
    { kana: "さく", romaji: "saku", meaning: "to blossom" },
    { kana: "さす", romaji: "sasu", meaning: "to open an umbrella" },
    { kana: "しぬ", romaji: "shinu", meaning: "to die, to pass away" },
    { kana: "しまる", romaji: "shimaru", meaning: "to close" },
    { kana: "しめる", romaji: "shimeru", meaning: "to close" },
    { kana: "しめる", romaji: "shimeru", meaning: "to fasten a belt" },
    { kana: "しる", romaji: "shiru", meaning: "to know" },
    { kana: "すう", romaji: "suu", meaning: "to breath, to smoke" },
    { kana: "すむ", romaji: "sumu", meaning: "to live, to reside somewhere" },
    { kana: "する", romaji: "suru", meaning: "to do" },
    { kana: "すわる", romaji: "suwaru", meaning: "to sit" },
    { kana: "だす", romaji: "dasu", meaning: "to take out, hand in" },
    { kana: "たつ", romaji: "tatsu", meaning: "to stand" },
    { kana: "たのむ", romaji: "tanomu", meaning: "to ask, to request" },
    { kana: "たべる", romaji: "taberu", meaning: "to eat" },
    { kana: "ちがう", romaji: "chigau", meaning: "to be different" },
    { kana: "つかう", romaji: "tsukau", meaning: "to use" },
    { kana: "つかれる", romaji: "tsukareru", meaning: "to get tired" },
    { kana: "つく", romaji: "tsuku", meaning: "to arrive" },
    { kana: "つくる", romaji: "tsukuru", meaning: "to make, to produce" },
    { kana: "つける", romaji: "tsukeru", meaning: "to turn on" },
    { kana: "つとめる", romaji: "tsutomeru", meaning: "to work for someone" },
    { kana: "でかける", romaji: "dekakeru", meaning: "to go out" },
    { kana: "できる", romaji: "dekiru", meaning: "can do" },
    { kana: "でる", romaji: "deru", meaning: "to leave" },
    { kana: "とぶ", romaji: "tobu", meaning: "to fly" },
    { kana: "とまる", romaji: "tomaru", meaning: "to stop" },
    { kana: "とる", romaji: "toru", meaning: "to take" },
    { kana: "とる", romaji: "toru", meaning: "to take a photo" },
    { kana: "なく", romaji: "naku", meaning: "to sing, mew, moo" },
    { kana: "ならぶ", romaji: "narabu", meaning: "to form a line" },
    { kana: "ならべる", romaji: "naraberu", meaning: "to line up" },
    { kana: "なる", romaji: "naru", meaning: "to become" },
    { kana: "ぬぐ", romaji: "nugu", meaning: "to take off clothes" },
    { kana: "ねる", romaji: "neru", meaning: "to sleep" },
    { kana: "のぼる", romaji: "noboru", meaning: "to climb up" },
    { kana: "のむ", romaji: "nomu", meaning: "to drink" },
    { kana: "のる", romaji: "noru", meaning: "to take, to ride" },
    { kana: "はいる", romaji: "hairu", meaning: "to enter" },
    { kana: "はく", romaji: "haku", meaning: "to put on shoes" },
    { kana: "はじまる", romaji: "hajimaru", meaning: "to begin, to start" },
    { kana: "はしる", romaji: "hashiru", meaning: "to run" },
    { kana: "はたらく", romaji: "hataraku", meaning: "to work" },
    { kana: "はなす", romaji: "hanasu", meaning: "to talk, to speak, to tell" },
    { kana: "はる", romaji: "haru", meaning: "to put something on, to stick" },
    { kana: "はれる", romaji: "hareru", meaning: "to clear up" },
    { kana: "ひく", romaji: "hiku", meaning: "to pull" },
    { kana: "ひく", romaji: "hiku", meaning: "to play an instrument" },
    { kana: "ふく", romaji: "fuku", meaning: "to blow (wind" },
    { kana: "ふる", romaji: "furu", meaning: "to fall (rain, snow" },
    { kana: "まがる", romaji: "magaru", meaning: "to turn" },
    { kana: "まつ", romaji: "matsu", meaning: "to wait" },
    { kana: "みがく", romaji: "migaku", meaning: "to polish, to brush" },
    { kana: "みせる", romaji: "miseru", meaning: "to show" },
    { kana: "みる", romaji: "miru", meaning: "to see, to watch" },
    { kana: "もつ", romaji: "motsu", meaning: "to have, to own" },
    { kana: "やすむ", romaji: "yasumu", meaning: "to rest" },
    { kana: "やる", romaji: "yaru", meaning: "to do" },
    { kana: "よぶ", romaji: "yobu", meaning: "to call" },
    { kana: "よむ", romaji: "yomu", meaning: "to read" },
    { kana: "わかる", romaji: "wakaru", meaning: "to know, to understand" },
    { kana: "わすれる", romaji: "wasureru", meaning: "to forget" },
    { kana: "わたす", romaji: "watasu", meaning: "to hand over" },
    { kana: "わたる", romaji: "wataru", meaning: "to cross" },
    { kana: "あう", romaji: "au", meaning: "to meet" },
    { kana: "あおい", romaji: "aoi", meaning: "blue" },
    { kana: "あかい", romaji: "akai", meaning: "red" },
    { kana: "あかるい", romaji: "akarui", meaning: "light, bright" },
    { kana: "あき", romaji: "aki", meaning: "autumn, fall" },
    { kana: "あく", romaji: "aku", meaning: "open" },
    { kana: "あける", romaji: "akeru", meaning: "to open" },
    { kana: "あげる", romaji: "ageru", meaning: "to give" },
    { kana: "あさ", romaji: "asa", meaning: "morning" },
    { kana: "あさごはん", romaji: "asagohan", meaning: "breakfast" },
    { kana: "あした", romaji: "ashita", meaning: "tomorrow" },
    { kana: "あそこ", romaji: "asoko", meaning: "over there" },
    { kana: "あそぶ", romaji: "asobu", meaning: "to play" },
    { kana: "あたたかい", romaji: "atatakai", meaning: "warm" },
    { kana: "あたま", romaji: "atama", meaning: "head" },
    { kana: "あたらしい", romaji: "atarashii", meaning: "new" },
    { kana: "あつい", romaji: "atsui", meaning: "hot (air)" },
    { kana: "あつい", romaji: "atsui", meaning: "thick" },
    { kana: "あに", romaji: "ani", meaning: "older brother" },
    { kana: "あね", romaji: "ane", meaning: "older sister" },
    { kana: "あの", romaji: "ano", meaning: "that (over there)" },
    { kana: "あの", romaji: "ano", meaning: "well, then" },
    { kana: "あぶない", romaji: "abunai", meaning: "dangerous" },
    { kana: "あまい", romaji: "amai", meaning: "sweet" },
    { kana: "あまり", romaji: "amari", meaning: "not so" },
    { kana: "あめ", romaji: "ame", meaning: "rain" },
    { kana: "ある", romaji: "aru", meaning: "to possess" },
    { kana: "あるく", romaji: "aruku", meaning: "to walk" },
    { kana: "あれ", romaji: "are", meaning: "that one" },
    { kana: "いいえ", romaji: "iie", meaning: "no" },
    { kana: "いえ", romaji: "ie", meaning: "house, home" },
    { kana: "いく", romaji: "iku", meaning: "to go" },
    { kana: "いくら", romaji: "ikura", meaning: "how much" },
    { kana: "いけ", romaji: "ike", meaning: "pond" },
    { kana: "いしゃ", romaji: "isha", meaning: "doctor" },
    { kana: "いす", romaji: "isu", meaning: "chair" },
    { kana: "いち", romaji: "ichi", meaning: "one" },
    { kana: "いつ", romaji: "itsu", meaning: "when" },
    { kana: "いつつ", romaji: "itsutsu", meaning: "five" },
    { kana: "いつも", romaji: "itsumo", meaning: "always" },
    { kana: "いま", romaji: "ima", meaning: "now" },
    { kana: "いみ", romaji: "imi", meaning: "meaning" },
    { kana: "いる", romaji: "iru", meaning: "to exist" },
    { kana: "いろ", romaji: "iro", meaning: "color" },
    { kana: "いろいろ", romaji: "iroiro", meaning: "various" },
    { kana: "うすい", romaji: "usui", meaning: "thin" },
    { kana: "うた", romaji: "uta", meaning: "song" },
    { kana: "うたう", romaji: "utau", meaning: "to sing" },
    { kana: "うち", romaji: "uchi", meaning: "home" },
    { kana: "うみ", romaji: "umi", meaning: "sea" },
    { kana: "うる", romaji: "uru", meaning: "to sell" },
    { kana: "うわぎ", romaji: "uwagi", meaning: "coat, jacket" },
    { kana: "え", romaji: "e", meaning: "picture" },
    { kana: "えいが", romaji: "eiga", meaning: "movie" },
    { kana: "えいがかん", romaji: "eigakan", meaning: "cinema" },
    { kana: "えいご", romaji: "eigo", meaning: "English language" },
    { kana: "えき", romaji: "eki", meaning: "station" },
    { kana: "えん", romaji: "en", meaning: "Yen" },
    { kana: "おいしい", romaji: "oishii", meaning: "tasty, delicious" },
    { kana: "おおぜい", romaji: "oozei", meaning: "many people" },
    { kana: "おかし", romaji: "okashi", meaning: "confectionary, cake" },
    { kana: "おくさん", romaji: "okusan", meaning: "someone’s wife" },
    { kana: "おくる", romaji: "okuru", meaning: "to send" },
    { kana: "おさけ", romaji: "osake", meaning: "alcohol, sake" },
    { kana: "おさら", romaji: "osara", meaning: "plate" },
    { kana: "おじいさん", romaji: "ojiisan", meaning: "grand father" },
    { kana: "おす", romaji: "osu", meaning: "to push" },
    { kana: "おそい", romaji: "osoi", meaning: "late, slow" },
    { kana: "おちゃ", romaji: "ocha", meaning: "tea" },
    { kana: "おてあらい", romaji: "otearai", meaning: "toilet, lavatory" },
    { kana: "おとうさん", romaji: "otousan", meaning: "father" },
    { kana: "おとこ", romaji: "otoko", meaning: "man" },
    { kana: "おとこのこ", romaji: "otokonoko", meaning: "boy" },
    { kana: "おとな", romaji: "otona", meaning: "adult" },
    { kana: "おなじ", romaji: "onaji", meaning: "same" },
    { kana: "おばさん", romaji: "obasan", meaning: "aunt" },
    { kana: "おばあさん", romaji: "obaasan", meaning: "grandmother" },
    { kana: "おべんとう", romaji: "obentou", meaning: "lunchbox" },
    { kana: "おもい", romaji: "omoi", meaning: "heavy" },
    { kana: "おもしろい", romaji: "omoshiroi", meaning: "interesting, funny" },
    { kana: "およぐ", romaji: "oyogu", meaning: "to swim" },
    { kana: "おわる", romaji: "owaru", meaning: "to end" },
    { kana: "おんがく", romaji: "ongaku", meaning: "music" },
    { kana: "おんな", romaji: "onna", meaning: "woman" },
    { kana: "おんなのこ", romaji: "onnanoko", meaning: "girl" },
    { kana: "がいこく", romaji: "gaikoku", meaning: "foreign country" },
    { kana: "がいこくじん", romaji: "gaikokujin", meaning: "foreigner" },
    { kana: "かいしゃ", romaji: "kaisha", meaning: "company, enterprise" },
    { kana: "かいだん", romaji: "kaidan", meaning: "stairs" },
    { kana: "かう", romaji: "kau", meaning: "to buy" },
    { kana: "かお", romaji: "kao", meaning: "face" },
    { kana: "かぎ", romaji: "kagi", meaning: "key" },
    { kana: "かく", romaji: "kaku", meaning: "to write" },
    { kana: "がくせい", romaji: "gakusei", meaning: "student" },
    { kana: "かける", romaji: "kakeru", meaning: "to wear" },
    { kana: "かさ", romaji: "kasa", meaning: "umbrella" },
    { kana: "かす", romaji: "kasu", meaning: "to lend" },
    { kana: "かぜ", romaji: "kaze", meaning: "wind" },
    { kana: "かぜ", romaji: "kaze", meaning: "a cold" },
    { kana: "かぞく", romaji: "kazoku", meaning: "family" },
    { kana: "かた", romaji: "kata", meaning: "person (polite)" },
    { kana: "かたかな", romaji: "katakana", meaning: "Katakana" },
    { kana: "いちがつ", romaji: "ichigatsu", meaning: "January" },
    { kana: "にがつ", romaji: "nigatsu", meaning: "February" },
    { kana: "さんがつ", romaji: "sangatsu", meaning: "March" },
    { kana: "しがつ", romaji: "shigatsu", meaning: "April" },
    { kana: "ごがつ", romaji: "gogatsu", meaning: "May" },
    { kana: "ろくがつ", romaji: "rokugatsu", meaning: "June" },
    { kana: "しちがつ", romaji: "shichigatsu", meaning: "July" },
    { kana: "はちがつ", romaji: "hachigatsu", meaning: "August" },
    { kana: "くがつ", romaji: "kugatsu", meaning: "September" },
    { kana: "じゅうがつ", romaji: "juugatsu", meaning: "October" },
    { kana: "じゅういちがつ", romaji: "juuichigatsu", meaning: "November" },
    { kana: "じゅうにがつ", romaji: "juunigatsu", meaning: "December" },
    { kana: "がっこう", romaji: "gakkou", meaning: "school" },
    { kana: "かど", romaji: "kado", meaning: "corner" },
    { kana: "かない", romaji: "kanai", meaning: "my wife" },
    { kana: "かばん", romaji: "kaban", meaning: "bag" },
    { kana: "かびん", romaji: "kabin", meaning: "vase" },
    { kana: "かみ", romaji: "kami", meaning: "paper" },
    { kana: "かめら", romaji: "kamera", meaning: "camera" },
    { kana: "かようび", romaji: "kayoubi", meaning: "Tuesday" },
    { kana: "からい", romaji: "karai", meaning: "hot, spicy" },
    { kana: "からだ", romaji: "karada", meaning: "body" },
    { kana: "かりる", romaji: "kariru", meaning: "to borrow" },
    { kana: "かるい", romaji: "karui", meaning: "light (not heavy)" },
    { kana: "かわ", romaji: "kawa", meaning: "river" },
    { kana: "き", romaji: "ki", meaning: "tree" },
    { kana: "きいろい", romaji: "kiiroi", meaning: "yellow" },
    { kana: "きた", romaji: "kita", meaning: "north" },
    { kana: "きたない", romaji: "kitanai", meaning: "dirty" },
    { kana: "きっさてん", romaji: "kissaten", meaning: "coffee shop" },
    { kana: "きって", romaji: "kitte", meaning: "stamp" },
    { kana: "きっぷ", romaji: "kippu", meaning: "ticket" },
    { kana: "きのう", romaji: "kinou", meaning: "yesterday" },
    { kana: "きゅう", romaji: "kyuu", meaning: "nine" },
    { kana: "ぎゅうにく", romaji: "gyuuniku", meaning: "beef" },
    { kana: "ぎゅうにゅう", romaji: "gyuunyuu", meaning: "milk" },
    { kana: "きょう", romaji: "kyou", meaning: "today" },
    { kana: "きょうしつ", romaji: "kyoushitsu", meaning: "class room" },
    { kana: "きょうだい", romaji: "kyoudai", meaning: "siblings" },
    { kana: "きょねん", romaji: "kyonen", meaning: "last year" },
    { kana: "きる", romaji: "kiru", meaning: "to cut" },
    { kana: "くる", romaji: "kuru", meaning: "to come" },
    { kana: "きれい", romaji: "kirei", meaning: "beautiful, clean" },
    { kana: "ぎんこう", romaji: "ginkou", meaning: "bank" },
    { kana: "きんようび", romaji: "kinyoubi", meaning: "Friday" },
    { kana: "く", romaji: "ku", meaning: "nine" },
    { kana: "くすり", romaji: "kusuri", meaning: "medicine" },
    { kana: "ください", romaji: "kudasai", meaning: "give me…" },
    { kana: "くだもの", romaji: "kudamono", meaning: "fruit" },
    { kana: "くち", romaji: "kuchi", meaning: "mouth" },
    { kana: "くつ", romaji: "kutsu", meaning: "shoe" },
    { kana: "くつした", romaji: "kutsushita", meaning: "socks" },
    { kana: "くに", romaji: "kuni", meaning: "country" },
    { kana: "くもり", romaji: "kumori", meaning: "cloudy weather" },
    { kana: "くらい", romaji: "kurai", meaning: "dark" },
    { kana: "ぐらい", romaji: "gurai", meaning: "about" },
    { kana: "くるま", romaji: "kuruma", meaning: "car" },
    { kana: "くろい", romaji: "kuroi", meaning: "black" },
    { kana: "けさ", romaji: "kesa", meaning: "this morning" },
    { kana: "けっこん", romaji: "kekkon", meaning: "marriage" },
    { kana: "げつようび", romaji: "getsuyoubi", meaning: "Monday" },
    { kana: "ご", romaji: "go", meaning: "five" },
    { kana: "こうばん", romaji: "kouban", meaning: "police box" },
    { kana: "こえ", romaji: "koe", meaning: "voice" },
    { kana: "ここ", romaji: "koko", meaning: "here" },
    { kana: "ごご", romaji: "gogo", meaning: "afternoon" },
    { kana: "ここのつ", romaji: "kokonotsu", meaning: "nine" },
    { kana: "ごぜん", romaji: "gozen", meaning: "morning, a.m." },
    { kana: "こたえる", romaji: "kotaeru", meaning: "to answer" },
    { kana: "ことし", romaji: "kotoshi", meaning: "this year" },
    { kana: "ことば", romaji: "kotoba", meaning: "phrase, language" },
    { kana: "こども", romaji: "kodomo", meaning: "child" },
    { kana: "この", romaji: "kono", meaning: "this…" },
    { kana: "これ", romaji: "kore", meaning: "this" },
    { kana: "ごろ", romaji: "goro", meaning: "around…" },
    { kana: "こんげつ", romaji: "kongetsu", meaning: "this month" },
    { kana: "こんしゅう", romaji: "konshuu", meaning: "this week" },
    { kana: "こんばん", romaji: "konban", meaning: "this evening" },
    { kana: "さあ", romaji: "saa", meaning: "well…" },
    { kana: "さかな", romaji: "sakana", meaning: "fish" },
    { kana: "さき", romaji: "saki", meaning: "earlier, former" },
    { kana: "さく", romaji: "saku", meaning: "to blossom" },
    { kana: "さくぶん", romaji: "sakubun", meaning: "composition" },
    { kana: "ざっし", romaji: "zasshi", meaning: "magazine" },
    { kana: "さとう", romaji: "satou", meaning: "sugar" },
    { kana: "さむい", romaji: "samui", meaning: "cold" },
    { kana: "さん", romaji: "san", meaning: "three" },
    { kana: "し", romaji: "shi", meaning: "four" },
    { kana: "しお", romaji: "shio", meaning: "salt" },
    { kana: "しかし", romaji: "shikashi", meaning: "however, but" },
    { kana: "じかん", romaji: "jikan", meaning: "time" },
    { kana: "しごと", romaji: "shigoto", meaning: "work" },
    { kana: "じしょ", romaji: "jisho", meaning: "dictionary" },
    { kana: "しずか", romaji: "shizuka", meaning: "quiet" },
    { kana: "した", romaji: "shita", meaning: "under, below" },
    { kana: "しつもん", romaji: "shitsumon", meaning: "question" },
    { kana: "じてんしゃ", romaji: "jitensha", meaning: "bicycle" },
    { kana: "じどうしゃ", romaji: "jidousha", meaning: "car, vehicle" },
    { kana: "じびき", romaji: "jibiki", meaning: "dictionary" },
    { kana: "じぶん", romaji: "jibun", meaning: "oneself" },
    { kana: "しまる", romaji: "shimaru", meaning: "to close" },
    { kana: "しめる", romaji: "shimeru", meaning: "to close" },
    { kana: "じゃ", romaji: "ja", meaning: "well, then" },
    { kana: "しゃしん", romaji: "shashin", meaning: "photo" },
    { kana: "じゅう", romaji: "juu", meaning: "ten" },
    { kana: "じゅぎょう", romaji: "jugyou", meaning: "lesson, class" },
    { kana: "しゅくだい", romaji: "shukudai", meaning: "homework" },
    { kana: "しょうゆ", romaji: "shouyu", meaning: "soy sauce" },
    { kana: "しる", romaji: "shiru", meaning: "to know" },
    { kana: "しろい", romaji: "shiroi", meaning: "white" },
    { kana: "しんぶん", romaji: "shinbun", meaning: "newspaper" },
    { kana: "すいようび", romaji: "suiyoubi", meaning: "Wednesday" },
    { kana: "すき", romaji: "suki", meaning: "to like" },
    { kana: "すこし", romaji: "sukoshi", meaning: "a little" },
    { kana: "すずしい", romaji: "suzushii", meaning: "cool" },
    { kana: "する", romaji: "suru", meaning: "to do" },
    { kana: "すわる", romaji: "suwaru", meaning: "to sit" },
    { kana: "せい", romaji: "sei", meaning: "height" },
    { kana: "せいと", romaji: "seito", meaning: "student" },
    { kana: "せっけん", romaji: "sekken", meaning: "soap" },
    { kana: "せびろ", romaji: "sebiro", meaning: "jacket, suit" },
    { kana: "せまい", romaji: "semai", meaning: "narrow" },
    { kana: "せん", romaji: "sen", meaning: "1,000, thousand" },
    { kana: "せんげつ", romaji: "sengetsu", meaning: "last month" },
    { kana: "せんしゅう", romaji: "senshuu", meaning: "last week" },
    { kana: "せんせい", romaji: "sensei", meaning: "teacher" },
    { kana: "ぜんぶ", romaji: "zenbu", meaning: "all" },
    { kana: "そう", romaji: "sou", meaning: "so" },
    { kana: "そうじ", romaji: "souji", meaning: "to clean" },
    { kana: "そうして", romaji: "soushite", meaning: "and then" },
    { kana: "そこ", romaji: "soko", meaning: "there" },
    { kana: "そちら", romaji: "sochira", meaning: "there (polite)" },
    { kana: "そと", romaji: "soto", meaning: "outside" },
    { kana: "その", romaji: "sono", meaning: "that…" },
    { kana: "そば", romaji: "soba", meaning: "next to" },
    { kana: "そら", romaji: "sora", meaning: "sky" },
    { kana: "それ", romaji: "sore", meaning: "that" },
    { kana: "それから", romaji: "sorekara", meaning: "after that" },
    { kana: "それでは", romaji: "soredewa", meaning: "then, well" },
    { kana: "だいがく", romaji: "daigaku", meaning: "university" },
    { kana: "たいしかん", romaji: "taishikan", meaning: "embassy" },
    { kana: "だいじょうぶ", romaji: "daijoubu", meaning: "OK" },
    { kana: "たいせつ", romaji: "taisetsu", meaning: "very important" },
    { kana: "たいてい", romaji: "taitei", meaning: "mostly, usually" },
    { kana: "だいどころ", romaji: "daidokoro", meaning: "kitchen" },
    { kana: "たいへん", romaji: "taihen", meaning: "very, serious" },
    { kana: "たかい", romaji: "takai", meaning: "high, expensive" },
    { kana: "たくさん", romaji: "takusan", meaning: "many, much" },
    { kana: "タクシー", romaji: "takushii", meaning: "taxi" },
    { kana: "たつ", romaji: "tatsu", meaning: "to stand" },
    { kana: "たてもの", romaji: "tatemono", meaning: "building" },
    { kana: "たのしい", romaji: "tanoshii", meaning: "pleasant, enjoyable" },
    { kana: "たばこ", romaji: "tabako", meaning: "cigarette" },
    { kana: "たぶん", romaji: "tabun", meaning: "perhaps, probably" },
    { kana: "たべもの", romaji: "tabemono", meaning: "food" },
    { kana: "たべる", romaji: "taberu", meaning: "to eat" },
    { kana: "たまご", romaji: "tamago", meaning: "egg" },
    { kana: "だれ", romaji: "dare", meaning: "who?" },
    { kana: "たんじょうび", romaji: "tanjoubi", meaning: "birthday" },
    { kana: "だんだん", romaji: "dandan", meaning: "gradually" },
    { kana: "ちいさい", romaji: "chiisai", meaning: "small" },
    { kana: "ちかい", romaji: "chikai", meaning: "near, close" },
    { kana: "ちがう", romaji: "chigau", meaning: "different" },
    { kana: "ちかてつ", romaji: "chikatetsu", meaning: "subway" },
    { kana: "ちず", romaji: "chizu", meaning: "map" },
    { kana: "ちち", romaji: "chichi", meaning: "my father" },
    { kana: "ちゃいろ", romaji: "chairo", meaning: "brown" },
    { kana: "ちゃわん", romaji: "chawan", meaning: "rice bowl" },
    { kana: "ちょうど", romaji: "choudo", meaning: "just" },
    { kana: "ちょっと", romaji: "chotto", meaning: "a little" },
    { kana: "つかう", romaji: "tsukau", meaning: "to use" },
    { kana: "つぎ", romaji: "tsugi", meaning: "next" },
    { kana: "つく", romaji: "tsuku", meaning: "to arrive" },
    { kana: "つくえ", romaji: "tsukue", meaning: "table" },
    { kana: "つまらない", romaji: "tsumaranai", meaning: "uninteresting" },
    { kana: "つめたい", romaji: "tsumetai", meaning: "cold" },
    { kana: "つよい", romaji: "tsuyoi", meaning: "strong" },
    { kana: "て", romaji: "te", meaning: "hand" },
    { kana: "てがみ", romaji: "tegami", meaning: "letter" },
    { kana: "できる", romaji: "dekiru", meaning: "can" },
    { kana: "でぐち", romaji: "deguchi", meaning: "exit" },
    { kana: "では", romaji: "dewa", meaning: "then, well" },
    { kana: "でも", romaji: "demo", meaning: "but" },
    { kana: "でます", romaji: "demasu", meaning: "to leave" },
    { kana: "てんき", romaji: "tenki", meaning: "weather" },
    { kana: "でんき", romaji: "denki", meaning: "electricity" },
    { kana: "でんしゃ", romaji: "densha", meaning: "train" },
    { kana: "でんわ", romaji: "denwa", meaning: "phone" },
    { kana: "と", romaji: "to", meaning: "door" },
    { kana: "どう", romaji: "dou", meaning: "how?" },
    { kana: "どうして", romaji: "doushite", meaning: "why?" },
    { kana: "どうぶつ", romaji: "doubutsu", meaning: "animal" },
    { kana: "どうも", romaji: "doumo", meaning: "thanks" },
    { kana: "とお", romaji: "too", meaning: "ten" },
    { kana: "とおい", romaji: "tooi", meaning: "far" },
    { kana: "ときどき", romaji: "tokidoki", meaning: "sometimes" },
    { kana: "とけい", romaji: "tokei", meaning: "watch, clock" },
    { kana: "どこ", romaji: "doko", meaning: "where?" },
    { kana: "ところ", romaji: "tokoro", meaning: "place" },
    { kana: "としょかん", romaji: "toshokan", meaning: "library" },
    { kana: "どなた", romaji: "donata", meaning: "who (polite)" },
    { kana: "となり", romaji: "tonari", meaning: "next to" },
    { kana: "どの", romaji: "dono", meaning: "which?" },
    { kana: "とぶ", romaji: "tobu", meaning: "to fly" },
    { kana: "とまる", romaji: "tomaru", meaning: "to stop" },
    { kana: "ともだち", romaji: "tomodachi", meaning: "friend" },
    { kana: "どようび", romaji: "doyoubi", meaning: "Saturday" },
    { kana: "とり", romaji: "tori", meaning: "bird" },
    { kana: "とりにく", romaji: "toriniku", meaning: "chicken meat" },
    { kana: "とる", romaji: "toru", meaning: "to take" },
    { kana: "どれ", romaji: "dore", meaning: "which?" },
    { kana: "なか", romaji: "naka", meaning: "inside" },
    { kana: "ながい", romaji: "nagai", meaning: "long" },
    { kana: "なつ", romaji: "natsu", meaning: "summer" },
    { kana: "なつやすみ", romaji: "natsuyasumi", meaning: "summer vacation" },
    { kana: "ななつ", romaji: "nanatsu", meaning: "seven" },
    { kana: "なに", romaji: "nani", meaning: "what?" },
    { kana: "なまえ", romaji: "namae", meaning: "name" },
    { kana: "ならう", romaji: "narau", meaning: "to learn" },
    { kana: "なる", romaji: "naru", meaning: "to become" },
    { kana: "に", romaji: "ni", meaning: "two" },
    { kana: "にぎやか", romaji: "nigiyaka", meaning: "lively" },
    { kana: "おにく", romaji: "oniku", meaning: "meat" },
    { kana: "にし", romaji: "nishi", meaning: "west" },
    { kana: "にちようび", romaji: "nichiyoubi", meaning: "Sunday" },
    { kana: "にもつ", romaji: "nimotsu", meaning: "luggage" },
    { kana: "にわ", romaji: "niwa", meaning: "garden" },
    { kana: "のみもの", romaji: "nomimono", meaning: "drinks" },
    { kana: "のむ", romaji: "nomu", meaning: "to drink" },
    { kana: "は", romaji: "ha", meaning: "teeth" },
    { kana: "はい", romaji: "hai", meaning: "yes" },
    { kana: "はいざら", romaji: "haizara", meaning: "ashtray" },
    { kana: "はいる", romaji: "hairu", meaning: "to enter" },
    { kana: "はがき", romaji: "hagaki", meaning: "postcard" },
    { kana: "はこ", romaji: "hako", meaning: "box" },
    { kana: "はし", romaji: "hashi", meaning: "bridge" },
    { kana: "はし", romaji: "hashi", meaning: "chopsticks" },
    { kana: "はしる", romaji: "hashiru", meaning: "to run" },
    { kana: "はたらく", romaji: "hataraku", meaning: "to work" },
    { kana: "はち", romaji: "hachi", meaning: "eight" },
    { kana: "はな", romaji: "hana", meaning: "flower" },
    { kana: "はな", romaji: "hana", meaning: "nose" },
    { kana: "はなし", romaji: "hanashi", meaning: "conversation, tale" },
    { kana: "はは", romaji: "haha", meaning: "my mother" },
    { kana: "はやい", romaji: "hayai", meaning: "early" },
    { kana: "はやい", romaji: "hayai", meaning: "fast, quick" },
    { kana: "ばん", romaji: "ban", meaning: "evening" },
    { kana: "ばんごう", romaji: "bangou", meaning: "number" },
    { kana: "ばんごはん", romaji: "bangohan", meaning: "dinner" },
    { kana: "はんぶん", romaji: "hanbun", meaning: "half" },
    { kana: "ひがし", romaji: "higashi", meaning: "east" },
    { kana: "ひく", romaji: "hiku", meaning: "to pull" },
    { kana: "ひくい", romaji: "hikui", meaning: "low" },
    { kana: "ひこうき", romaji: "hikouki", meaning: "plane" },
    { kana: "ひだり", romaji: "hidari", meaning: "left" },
    { kana: "ひと", romaji: "hito", meaning: "person" },
    { kana: "ひとつ", romaji: "hitotsu", meaning: "one" },
    { kana: "ひとつき", romaji: "hitotsuki", meaning: "one month" },
    { kana: "ひとり", romaji: "hitori", meaning: "one person" },
    { kana: "ひゃく", romaji: "hyaku", meaning: "hundred" },
    { kana: "びょういん", romaji: "byouin", meaning: "hospital" },
    { kana: "びょうき", romaji: "byouki", meaning: "ill, sick" },
    { kana: "ひる", romaji: "hiru", meaning: "noon" },
    { kana: "ひるごはん", romaji: "hirugohan", meaning: "lunch" },
    { kana: "ひろい", romaji: "hiroi", meaning: "wide, spacious" },
    { kana: "ふうとう", romaji: "fuutou", meaning: "envelope" },
    { kana: "ふく", romaji: "fuku", meaning: "clothes" },
    { kana: "ふたつ", romaji: "futatsu", meaning: "two" },
    { kana: "ぶたにく", romaji: "butaniku", meaning: "pork" },
    { kana: "ふたり", romaji: "futari", meaning: "two people" },
    { kana: "ふとい", romaji: "futoi", meaning: "thick, fat" },
    { kana: "ふるい", romaji: "furui", meaning: "old" },
    { kana: "おふろ", romaji: "ofuro", meaning: "bath" },
    { kana: "へや", romaji: "heya", meaning: "room" },
    { kana: "ぺん", romaji: "pen", meaning: "pen" },
    { kana: "べんきょう", romaji: "benkyou", meaning: "to study" },
    { kana: "べんり", romaji: "benri", meaning: "convenient" },
    { kana: "ぼうし", romaji: "boushi", meaning: "hat" },
    { kana: "ほか", romaji: "hoka", meaning: "another, other" },
    { kana: "ほそい", romaji: "hosoi", meaning: "thin, fine" },
    { kana: "ほん", romaji: "hon", meaning: "book" },
    { kana: "ほんだな", romaji: "hondana", meaning: "bookshelf" },
    { kana: "ほんとうに", romaji: "hontouni", meaning: "really" },
    { kana: "まいあさ", romaji: "maiasa", meaning: "every morning" },
    { kana: "まいしゅう", romaji: "maishuu", meaning: "every week" },
    { kana: "まいにち", romaji: "mainichi", meaning: "every day" },
    { kana: "まいばん", romaji: "maiban", meaning: "every evening" },
    { kana: "まえ", romaji: "mae", meaning: "front" },
    { kana: "まがる", romaji: "magaru", meaning: "to turn" },
    { kana: "まずい", romaji: "mazui", meaning: "bad tasting" },
    { kana: "また", romaji: "mata", meaning: "also, again" },
    { kana: "まだ", romaji: "mada", meaning: "not yet" },
    { kana: "まち", romaji: "machi", meaning: "city, town" },
    { kana: "まつ", romaji: "matsu", meaning: "to wait" },
    { kana: "まど", romaji: "mado", meaning: "window" },
    { kana: "まるい", romaji: "marui", meaning: "round" },
    { kana: "まん", romaji: "man", meaning: "ten thousand" },
    { kana: "まんねんひつ", romaji: "mannenhitsu", meaning: "fountain pen" },
    { kana: "みぎ", romaji: "migi", meaning: "correctAnswersCount" },
    { kana: "みじかい", romaji: "mijikai", meaning: "short" },
    { kana: "おみず", romaji: "omizu", meaning: "water" },
    { kana: "みせ", romaji: "mise", meaning: "shop" },
    { kana: "みち", romaji: "michi", meaning: "road" },
    { kana: "みっつ", romaji: "mittsu", meaning: "three" },
    { kana: "みなさん", romaji: "minasan", meaning: "everyone" },
    { kana: "みなみ", romaji: "minami", meaning: "south" },
    { kana: "みみ", romaji: "mimi", meaning: "ear" },
    { kana: "みんな", romaji: "minna", meaning: "all, everyone" },
    { kana: "むこう", romaji: "mukou", meaning: "over there" },
    { kana: "むずかしい", romaji: "muzukashii", meaning: "difficult" },
    { kana: "むっつ", romaji: "muttsu", meaning: "six" },
    { kana: "め", romaji: "me", meaning: "eye" },
    { kana: "もう", romaji: "mou", meaning: "already, yet" },
    { kana: "もう", romaji: "mou", meaning: "one more" },
    { kana: "もくようび", romaji: "mokuyoubi", meaning: "Thursday" },
    { kana: "もちろん", romaji: "mochiron", meaning: "of course" },
    { kana: "もっと", romaji: "motto", meaning: "more" },
    { kana: "もの", romaji: "mono", meaning: "thing" },
    { kana: "もん", romaji: "mon", meaning: "gate" },
    { kana: "もんだい", romaji: "mondai", meaning: "problem, question" },
    { kana: "やおや", romaji: "yaoya", meaning: "vegetable shop" },
    { kana: "やさい", romaji: "yasai", meaning: "vegetable" },
    { kana: "やさしい", romaji: "yasashii", meaning: "gentle" },
    { kana: "やすい", romaji: "yasui", meaning: "cheap, inexpensive" },
    { kana: "やすみ", romaji: "yasumi", meaning: "holiday, vacation" },
    { kana: "やすむ", romaji: "yasumu", meaning: "to rest" },
    { kana: "やっつ", romaji: "yattsu", meaning: "eight things" },
    { kana: "やま", romaji: "yama", meaning: "mountain" },
    { kana: "やる", romaji: "yaru", meaning: "to do" },
    { kana: "よく", romaji: "yoku", meaning: "often" },
    { kana: "よこ", romaji: "yoko", meaning: "horizontal" },
    { kana: "よっつ", romaji: "yottsu", meaning: "four" },
    { kana: "よぶ", romaji: "yobu", meaning: "to call" },
    { kana: "よむ", romaji: "yomu", meaning: "to read" },
    { kana: "よる", romaji: "yoru", meaning: "night" },
    { kana: "らいげつ", romaji: "raigetsu", meaning: "next month" },
    { kana: "らいしゅう", romaji: "raishuu", meaning: "next week" },
    { kana: "らいねん", romaji: "rainen", meaning: "next year" },
    { kana: "りっぱ", romaji: "rippa", meaning: "splendid" },
    { kana: "りゅうがくせい", romaji: "ryuugakusei", meaning: "foreign student" },
    { kana: "りょうしん", romaji: "ryoushin", meaning: "parents" },
    { kana: "りょうり", romaji: "ryouri", meaning: "cooking" },
    { kana: "りょこう", romaji: "ryokou", meaning: "travel" },
    { kana: "れい", romaji: "rei", meaning: "zero" },
    { kana: "れいぞうこ", romaji: "reizouko", meaning: "refrigerator" },
    { kana: "れんしゅう", romaji: "renshuu", meaning: "practice" },
    { kana: "ろく", romaji: "roku", meaning: "six" },
    { kana: "わかい", romaji: "wakai", meaning: "young" },
    { kana: "わすれる", romaji: "wasureru", meaning: "to forget" },
    { kana: "わたし", romaji: "watashi", meaning: "me, I" },
    { kana: "わたる", romaji: "wataru", meaning: "to cross" },
    { kana: "わるい", romaji: "warui", meaning: "bad" }
];